---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengyafei.
--- DateTime: 2022/8/16 2:09 下午
---

--- select('#', …) 返回可变参数的长度
--- select(n, …) 用于返回从起点 n 开始到结束位置的所有参数列表




--- ...代表可变参数
--- #arg 数组长度
--- select("#", ...) 数组长度


--- 方式1 #arg
function average(...)
    result = 0
    local arg = {...}
    for i, v in ipairs(arg) do
        result = result + v
    end
    print("总共传入".. #arg .."个数")
    return result/#arg
end

--- 方式2 select("#", ...)
function average_1(...)
    result = 0
    local arg = {...}
    for i, v in ipairs(arg) do
        result = result + v
    end
    print("总共传入".. select("#", ...) .."个数")
    return result/select("#", ...)
end

print("平均数：", average_1(1,1,1,2,1))


