---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengyafei.
--- DateTime: 2022/8/16 10:56 上午
---

---string
---number
---nil
---function
---function
---number
---number

print(type("Hello World!"))
print(type(10.4))
print(type(nil))
print(type(print))
print(type(type))
print(type(1))
print(type(10.4/2))


