---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengyafei.
--- DateTime: 2022/8/16 11:09 上午
---

function addNumber(number1, number2)
    return number1 + number2;
end

b = addNumber(1,2)

print(b)



