---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengyafei.
--- DateTime: 2022/8/16 2:01 下午
---

--- 找到数组中最大值 返回数值和坐标
function maxNumber(arrays)
    -- 定义数组起始位置
    local min = 1;
    local m = arrays[min]
    for i, v in ipairs(arrays) do
        if v > m then
            min = i
            m = v
        end
    end
    return m, min
end

print(maxNumber({1,3,5,2}))







