---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengyafei.
--- DateTime: 2022/8/16 3:22 下午
---


local mysql_driver = require "luasql.mysql"

--- 创建环境对象
env = mysql_driver:mysql()

--- 连接数据库
conn = env:connect("test","root","HA@bjca#01","192.168.16.4",3306)

--- 设置数据库的编码格式
conn:execute"SET NAMES UTF8"

--- 执行数据库操作
cur = conn:execute("select * from student_tbl")

row = cur:fetch({},"a")

--- 文件对象的创建
file = io.open("role.txt","w+");

while row do
    var = string.format("%d %s\n", row.id, row.name)

    print(var)

    file:write(var)

    row = cur:fetch(row,"a")
end


file:close()
conn:close()
env:close()

