---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengyafei.
--- DateTime: 2022/8/16 10:30 上午
---


print("Hello world")

print(type(X))

print(type(X) == nil)

print(type(X) == "nil")







