---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengyafei.
--- DateTime: 2022/8/16 1:55 下午
---

--- 返回查找到的起始和结束坐标 未发现返回nil
startIndex, endIndex = string.find("www.baidu.com", "co")
print(startIndex, endIndex)
--char = string.sub("www.baidu.com", string.find("www.baidu.com", "baidu"))
--print(char)

--- 大写
print(string.upper("hello world"))
--- 小写
print(string.lower("HeLLO"))
--- 替换 返回替换之后的值 替换次数
print(string.gsub("www.baidu.com", "w", "google"))
--- 反转
print(string.reverse("hello"))
--- 长度获取
print(string.len("hello"))
--- 连接两个字符串
print("hello " .. "world")
--- 匹配
--for word in string.gmatch("www.baidu.com", "google") do print(word) end
--print(string.gmatch("www.baidu.com", "baidu"))

print(string.match("www.baidu.com", "google"))












