---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fengyafei.
--- DateTime: 2022/8/16 10:30 上午
---

--- lua数组下标从1开始
--local tab = {"apple", "pear", "orange"}
--for key, value in ipairs(tab) do
--    print("key", key)
--end

--- table不会固定大小
local tab = {};
--print(tab)

for i = 1, 10 do
    tab[i] = i
end

for key, value in ipairs(tab) do
    print(key, value)
end
